### ISSUE TITLE
500 Error caused by private property $filesystem

### ISSUE THREAD

**Issue by lindner** [mapkyca/known-ipfs#4]
Plugin fails due to private $filesystem property.

Looks like this might be caused by Idno/known@ef797b39caff789c5a43b541180f1464e54b64f1

The technical details are as follows:
```
Fatal Error: /home/lindner/projects/known/Known/IdnoPlugins/IPFS/Main.php:30 - "Uncaught Error: Cannot access private property Idno\Core\Idno::$filesystem in /home/lindner/projects/known/Known/IdnoPlugins/IPFS/Main.php:30
Stack trace:
#0 /home/lindner/projects/known/Known/Idno/Common/Component.php(18): IdnoPlugins\IPFS\Main->registerEventHooks()
#1 /home/lindner/projects/known/Known/Idno/Core/Plugins.php(66): Idno\Common\Component->__construct()
#2 /home/lindner/projects/known/Known/Idno/Common/Component.php(17): Idno\Core\Plugins->init()
#3 /home/lindner/projects/known/Known/Idno/Core/Idno.php(254): Idno\Common\Component->__construct()
#4 /home/lindner/projects/known/Known/Idno/Common/Component.php(19): Idno\Core\Idno->registerPages()
#5 /home/lindner/projects/known/Known/Idno/Core/Idno.php(45): Idno\Common\Component->__construct()
#6 /home/lindner/projects/known/Known/Idno/start.php(149): Idno\Core\Idno->__construct()
#7 /home/lindner/projects/known/Known/index.php(25): require_once('/home/lindner/p...')
#8 {main}
```

**Comment by mapkyca** [comment]
Ahh, thanks for the heads up. 

Going to be a few plugins that need some tidying after the tidy up...

**Comment by mapkyca** [comment]
Ironically the IPFS and S3 plugins hijack the filesystem in precisely the way that the new member variable protection was designed to stop.

The "correct" way is to specify the filesystem in the config.ini (which is supported), so this line should just be able to be removed.
